require:
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Layout/LineLength:
  Max: 120
  AllowURI: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

GetText/DecorateString:
  Enabled: false

RailsI18n/DecorateString:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/
