version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_DB: rails_blog_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout

      - run:
          name: Copying ENV file
          command: cp .env.example .env

      - run:
          name: Which bundler?
          command: bin/bundle -v

      - restore_cache:
          keys:
            - rails-blog-{{ checksum "Gemfile.lock" }}
            - rails-blog-

      - run:
          name: Bundle Install
          command: bin/bundle check --path vendor/bundle || bin/bundle install --deployment

      - save_cache:
          key: rails-blog-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:setup --trace

      - run:
          name: Install Yarn Packages
          command: yarn install --check-files

      - run:
          name: Precompile Webpacker packages
          command: bin/rails webpacker:compile

      - run:
          name: Rubocop lint
          command: |
            bin/rubocop

      - run:
          name: RSpec
          command: |
            bin/rspec

      - store_test_results:
          path: test_results
